# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: xurei/hyperkeys-docker-build-image:latest

pipelines:
  branches:
    production:
      - step:
          script: # Modify the commands below to build your repository.
            - npm ci
            - npm run build
