name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run lint
    - run: rm -rf build || true; mkdir build
    - run: npm run build:dependencies
    - run: npm run build

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: rm -rf build || true; mkdir build
    - run: npm run build:dependencies
    - run: npm run build
    - run: pwd
    - run: npm run package:linux
      env:
        # This token is provided by Actions, you do not need to create your own token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USE_HARD_LINKS: false

#    - run: npm run package:windows
#    - name: Create Release
#      id: create_release
#      uses: actions/create-release@latest
#      env:
#        # This token is provided by Actions, you do not need to create your own token
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ github.ref }}
#        release_name: Release ${{ github.ref }}
#        draft: false
#        prerelease: false

