name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: rm -rf build || true; mkdir build
      - run: npm run build:dependencies
      - run: npm run build

  release-linux:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'v')

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: rm -rf build || true; mkdir build
      - run: npm run build:dependencies
      - run: npm run build
      - run: pwd
      - run: npm run package:linux
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_HARD_LINKS: false

  release-windows:
    runs-on: windows-2019
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ github.ref }}"
      - run: npm ci
      - run: npm run build:dependencies
      - run: npm run build
      - run: pwd
      - run: npm run package:windows
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_HARD_LINKS: false
