name: Prepare new version

on:
  release:
    types: [published]

jobs:
  create-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git pull origin master
      - run: npm version patch --no-git-tag-version
      - run: git add package.json && git add package-lock.json
      - run: git commit -m "Started New version development"
      - run: git push
