name: Prepare new version

on:
  release:
    types: [published]

jobs:
  create-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - run: npm version patch --no-git-tag-version
      - run: git commit --amend -m "Started New version development"
      - run: git push
